---
title: "Normalization figure"
author: "Tom van Schaik"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document:
    theme: journal #cerulean
    highlight: monochrome
    toc: true
    toc_float: true
    code_folding: show
  editor_options:
    chunk_output_type: console
---

### Introduction

This document will make the normalization figure.


### Method

Simple base-R plotting. Data to plot (K562) :

  * RepliSeq
  * G1
  * S
  * G2
  

### Set-up

Set the parameters and list the data.

```{r set-up}

# Load dependencies
suppressMessages(suppressWarnings(library(GenomicRanges)))
suppressMessages(suppressWarnings(library(rtracklayer)))
suppressMessages(suppressWarnings(library(ggplot2)))
suppressMessages(suppressWarnings(library(reshape2)))
suppressMessages(suppressWarnings(library(RColorBrewer)))
suppressMessages(suppressWarnings(library(grid)))
suppressMessages(suppressWarnings(library(gridExtra)))
suppressMessages(suppressWarnings(library(gtable)))


# 
# Prepare output
output_dir <- "ts191009_figure_track_RPE_shakeoff"
dir.create(output_dir, showWarnings = FALSE)

# Load the data sets required
file_names <- c("t_1h", "t_3h", "t_6h", "t_10h", "t_21h", "bulk", "damid")

bulk <- import("../ts190509_RPE_HCT116_synchronization/results/tracks/normalized/bin-80kb/pADamID-RPE_bulk_LMNB2-80kb-combined.bw")
damid <- import("~/mydata/proj/3D_nucleus/results/ts180110_4DN_DataProcessing/results/tracks/normalized/bin-80kb/RPE_LMNB1-80kb-combined.bw")
t_1h <- import("results/tracks/normalized/bin-80kb/pADamID-RPE_1h_LMNB2-80kb-combined.bw")
t_3h <- import("results/tracks/normalized/bin-80kb/pADamID-RPE_3h_LMNB2-80kb-combined.bw")
t_6h <- import("results/tracks/normalized/bin-80kb/pADamID-RPE_6h_LMNB2-80kb-combined.bw")
t_10h <- import("results/tracks/normalized/bin-80kb/pADamID-RPE_10h_LMNB2-80kb-combined.bw")
t_21h <- import("results/tracks/normalized/bin-80kb/pADamID-RPE_21h_LMNB2-80kb-combined.bw")

data_tracks <- list(t_1h, t_3h, t_6h, t_10h, t_21h, bulk, damid)
names(data_tracks) <- file_names

# Let's combine the various bigwig files into one
# First, create a GRanges with all the bins
bins <- read.table("../ts180813_GCF5083_pADamIDtests/results/counts/bin-80kb/DamID-Hap1_r1_Dam-80kb.counts.txt.gz",
                   sep = "\t")[, 1:3]
names(bins) <- c("seqnames", "start", "end")
bins$start <- bins$start + 1
bins <- as(bins, "GRanges")

# Add the data
mcols(bins)[, file_names] <- NA 

for (i in file_names) {
  track <- data_tracks[[i]]
  ovl <- findOverlaps(track, bins)
  if (! i == "repliseq") {
    mcols(bins)[subjectHits(ovl), i] <- scale(track$score[queryHits(ovl)])
  } else {
    mcols(bins)[subjectHits(ovl), i] <- track$score[queryHits(ovl)]
  }
}


```

```{r knits setup}
library(knitr)
opts_chunk$set(dev=c('png', 'pdf'), fig.path = file.path(output_dir, "figures/"))
pdf.options(useDingbats = FALSE)
```


### 1) Plot

Plot a particular example region.

```{r plot, fig.width = 6, fig.height = 6.5}

PlotDataTracks <- function(bins, chr = "chr1", start = 1, end = 1e6) {
  
  # Get the data
  data <- bins[seqnames(bins) == chr & 
                 start(bins) >= start & 
                 end(bins) <= end]
  
  data <- as(data, "data.frame")
  
  # Melt the data
  data.melt <- melt(data, id.vars = c("seqnames", "start", "end", "width", "strand"))
  data.melt <- data.melt[complete.cases(data.melt), ]
  
  # # I want a dummy to keep G1 -> G2 to same, while given RepliSeq freedom for the range
  # limits <- range(data.melt$value[data.melt$variable != "repliseq"])
  # dummy <- data.frame(xmin = data.melt$start[1], xmax = data.melt$end[1],
  #                     ymin = limits[1], ymax = limits[2],
  #                     variable = factor(c("g1", "s", "g2"),
  #                                       levels = levels(data.melt$variable)))
  
  
  # Plot the data
  plt <- ggplot(data.melt, aes(xmin = start / 1e6, xmax = end / 1e6, ymin = 0, ymax = value,
                               fill = variable)) +
    geom_rect() +
    geom_hline(yintercept = 0, size = 0.5) +
    # facet_grid(variable ~ ., scales = "free_y") +
    facet_grid(variable ~ .) +
    # geom_blank(data = dummy, aes(ymin = ymin, ymax = ymax)) +
    #facet_grid(variable ~ .) +
    xlab(paste0(chr, " (Mb)")) +
    ylab("Score") +
    scale_x_continuous(expand = c(0, 0)) + 
    scale_y_continuous(expand = c(0, 0)) +
    scale_fill_grey(guide = FALSE) +
    theme_classic()
  
  plot(plt)
  
}

PlotDataTracks(bins, 
               chr = "chr9", start = 85e6, end = 200e6)

PlotDataTracks(bins, 
               chr = "chr10", start = 0e6, end = 32e6)

PlotDataTracks(bins, 
               chr = "chr11", start = 0e6, end = 35e6)

PlotDataTracks(bins, 
               chr = "chr12", start = 75e6, end = 200e6)

PlotDataTracks(bins, 
               chr = "chr16", start = 68e6, end = 200e6)

PlotDataTracks(bins, 
               chr = "chr17", start = 50e6, end = 200e6)

PlotDataTracks(bins, 
               chr = "chrX", start = 80e6, end = 200e6)


```

```{r more data tracks, fig.width = 9, fig.height = 6.5}

PlotDataTracks <- function(bins, chr = "chr1", start = 1, end = 1e6) {
  
  # Get the data
  data <- bins[seqnames(bins) == chr & 
                 start(bins) >= start & 
                 end(bins) <= end]
  
  data <- as(data, "data.frame")
  
  # Melt the data
  data.melt <- melt(data, id.vars = c("seqnames", "start", "end", "width", "strand"))
  data.melt <- data.melt[complete.cases(data.melt), ]
  
  data.melt$class <- "timepoints"
  data.melt$class[data.melt$variable == "bulk"] <- "bulk-pADamID"
  data.melt$class[data.melt$variable == "damid"] <- "bulk-DamID"
  data.melt$class <- factor(data.melt$class,
                            levels = c("timepoints", "bulk-pADamID", "bulk-DamID"))
  
  # # I want a dummy to keep G1 -> G2 to same, while given RepliSeq freedom for the range
  # limits <- range(data.melt$value[data.melt$variable != "repliseq"])
  # dummy <- data.frame(xmin = data.melt$start[1], xmax = data.melt$end[1],
  #                     ymin = limits[1], ymax = limits[2],
  #                     variable = factor(c("g1", "s", "g2"),
  #                                       levels = levels(data.melt$variable)))
  
  
  # Plot the data
  plt <- ggplot(data.melt, aes(xmin = start / 1e6, xmax = end / 1e6, ymin = 0, ymax = value,
                               fill = class)) +
    geom_rect() +
    geom_hline(yintercept = 0, size = 0.5) +
    # facet_grid(variable ~ ., scales = "free_y") +
    facet_grid(variable ~ .) +
    # geom_blank(data = dummy, aes(ymin = ymin, ymax = ymax)) +
    #facet_grid(variable ~ .) +
    xlab(paste0(chr, " (Mb)")) +
    ylab("Lamina contacts") +
    scale_x_continuous(expand = c(0, 0)) + 
    scale_y_continuous(expand = c(0, 0)) +
    scale_fill_manual(values = c("#7379B7", "#3F479C", "#DD6E42"), guide = FALSE) +
    #scale_fill_grey(guide = FALSE) +
    theme_classic()
  
  plot(plt)
  
}

PlotDataTracks(bins, 
               chr = "chr2", start = 92e6, end = 250e6)

PlotDataTracks(bins, 
               chr = "chr15", start = 60e6, end = 95e6)

```

```{r whole chromosome, fig.width = 12, fig.height = 9}

PlotDataTracksWithLADs <- function(bins, LADs, chr = "chr1", start = 1, end = 1e6) {
  
  # Get the data
  data <- bins[seqnames(bins) == chr & 
                 start(bins) >= start & 
                 end(bins) <= end]
  
  data <- as(data, "data.frame")
  
  # Melt the data
  data.melt <- melt(data, id.vars = c("seqnames", "start", "end", "width", "strand"))
  data.melt <- data.melt[complete.cases(data.melt), ]
  
  data.melt$class <- "timepoints"
  data.melt$class[data.melt$variable == "bulk"] <- "bulk-pADamID"
  data.melt$class[data.melt$variable == "damid"] <- "bulk-DamID"
  data.melt$class <- factor(data.melt$class,
                            levels = c("timepoints", "bulk-pADamID", "bulk-DamID"))
  
  # # I want a dummy to keep G1 -> G2 to same, while given RepliSeq freedom for the range
  # limits <- range(data.melt$value[data.melt$variable != "repliseq"])
  # dummy <- data.frame(xmin = data.melt$start[1], xmax = data.melt$end[1],
  #                     ymin = limits[1], ymax = limits[2],
  #                     variable = factor(c("g1", "s", "g2"),
  #                                       levels = levels(data.melt$variable)))
  
  
  # Plot the data
  plt <- ggplot(data.melt, aes(xmin = start / 1e6, xmax = end / 1e6, ymin = 0, ymax = value,
                               fill = class)) +
    geom_rect() +
    geom_hline(yintercept = 0, size = 0.5) +
    # facet_grid(variable ~ ., scales = "free_y") +
    facet_grid(variable ~ .) +
    # geom_blank(data = dummy, aes(ymin = ymin, ymax = ymax)) +
    #facet_grid(variable ~ .) +
    xlab(paste0(chr, " (Mb)")) +
    ylab("Lamina contacts") +
    scale_x_continuous(expand = c(0, 0)) + 
    scale_y_continuous(expand = c(0, 0)) +
    scale_fill_manual(values = c("#7379B7", "#3F479C", "#DD6E42"), guide = FALSE) +
    #scale_fill_grey(guide = FALSE) +
    theme_classic()
  
  plot(plt)
  
  # Also make a plot with the LADs
  df <- LADs[seqnames(LADs) == chr & 
               start(LADs) >= start & 
               end(LADs) <= end]
  df <- as(df, "data.frame")
  #df <- df[df$result != "stable", ]
  
  plt2 <- ggplot(df, aes(xmin = start / 1e6, xmax = end / 1e6, ymin = 0, ymax = 1,
                         fill = result)) +
    geom_rect(col = NA) +
    xlab(paste0(chr, " (Mb)")) +
    facet_grid(1 ~ .) +
    ylab("LADs") +
    scale_x_continuous(expand = c(0, 0)) + 
    scale_y_continuous(expand = c(0, 0)) +
    scale_fill_manual(values = c("#E41A1C", "#999999", "#4DAF4A"), guide = FALSE) +
    theme_classic()
  
  #plot(plt2)
  
  plt <- ggplotGrob(plt)
  plt2 <- ggplotGrob(plt2)
  g <- rbind(plt, plt2, size = "first")
  g$widths <- unit.pmax(plt$widths, plt2$widths)
  grid.newpage()
  grid.draw(g)
  
}

# Get the LADs + differential call
LADs <- readRDS("ts190802_differential_analysis_BinsandLADs_RPE/LADs.rds")
LADs.result <- readRDS("ts190802_differential_analysis_BinsandLADs_RPE/LADs_results.rds")
LADs$result <- LADs.result[, 2]

# Rename
LADs$result[LADs$result == 0] <- "stable"
LADs$result[LADs$result == -1] <- "down"
LADs$result[LADs$result == 1] <- "up"
LADs$result <- factor(LADs$result, levels = c("down", "stable", "up"))

PlotDataTracksWithLADs(bins, LADs,
                       chr = "chr2", start = 0e6, end = 1e9)
PlotDataTracksWithLADs(bins, LADs,
                       chr = "chr3", start = 0e6, end = 1e9)

```


### Conclusion

I need to decide and change the colors. This might be easier in illustrator, so 
I won't bother with it now.


### SessionInfo

```{r sessionInfo}

sessionInfo()

```





















