---
title: "Data track figure"
author: "Tom van Schaik"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document:
    theme: journal #cerulean
    highlight: monochrome
    toc: true
    toc_float: true
    code_folding: show
  editor_options:
    chunk_output_type: console
---

### Introduction

This document will make the normalization figure.


### Method

Simple base-R plotting. Data to plot (Hap1, K562, HCT116, RPE) :

  * DamID
  * pA-DamID
  

### Set-up

Set the parameters and list the data.

```{r set-up}

# Load dependencies
suppressMessages(suppressWarnings(library(GenomicRanges)))
suppressMessages(suppressWarnings(library(rtracklayer)))
suppressMessages(suppressWarnings(library(ggplot2)))
suppressMessages(suppressWarnings(library(reshape2)))
suppressMessages(suppressWarnings(library(RColorBrewer)))


# 
# Prepare output
output_dir <- "ts190730_figure_track_pADamIDvsDamID"
dir.create(output_dir, showWarnings = FALSE)

# Load the data sets required
file_names <- c("Hap1_pADamID_LB1", "Hap1_pADamID_LB2", "Hap1_DamID", 
                "K562_pADamID_LB1", "K562_pADamID_LB2", "K562_DamID",
                "HCT116_pADamID_LB1", "HCT116_pADamID_LB2", "HCT116_DamID",
                "RPE_pADamID_LB1", "RPE_pADamID_LB2", "RPE_pADamID_LAC",
                "RPE_DamID")

Hap1_pADamID_LB1 <- import("results/tracks/normalized/bin-20kb/Hap1_LMNB1-20kb-combined.bw")
K562_pADamID_LB1 <- import("results/tracks/normalized/bin-20kb/K562_LMNB1-20kb-combined.bw")
HCT116_pADamID_LB1 <- import("results/tracks/normalized/bin-20kb/HCT116_LMNB1-20kb-combined.bw")
RPE_pADamID_LB1 <- import("../ts190509_RPE_HCT116_synchronization/results/tracks/normalized/bin-20kb/pADamID-RPE_bulk_LMNB1-20kb-combined.bw")

Hap1_pADamID_LB2 <- import("results/tracks/normalized/bin-20kb/Hap1_LMNB2-20kb-combined.bw")
K562_pADamID_LB2 <- import("results/tracks/normalized/bin-20kb/K562_LMNB2-20kb-combined.bw")
HCT116_pADamID_LB2 <- import("results/tracks/normalized/bin-20kb/HCT116_LMNB2-20kb-combined.bw")
RPE_pADamID_LB2 <- import("../ts190509_RPE_HCT116_synchronization/results/tracks/normalized/bin-20kb/pADamID-RPE_bulk_LMNB2-20kb-combined.bw")

RPE_pADamID_LAC <- import("../ts190509_RPE_HCT116_synchronization/results/tracks/normalized/bin-20kb/pADamID-RPE_bulk_LMNAC-20kb-combined.bw")

Hap1_DamID <- import("~/mydata/proj/3D_nucleus/results/ts180110_4DN_DataProcessing/results/tracks/normalized/bin-20kb/Hap1_LMNB1-20kb-combined.bw")
K562_DamID <- import("~/mydata/proj/3D_nucleus/results/ts180110_4DN_DataProcessing/results/tracks/normalized/bin-20kb/K562_LMNB1-20kb-combined.bw")
HCT116_DamID <- import("~/mydata/proj/3D_nucleus/results/ts180110_4DN_DataProcessing/results/tracks/normalized/bin-20kb/HCT116_LMNB1-20kb-combined.bw")
RPE_DamID <- import("~/mydata/proj/3D_nucleus/results/ts180110_4DN_DataProcessing/results/tracks/normalized/bin-20kb/RPE_LMNB1-20kb-combined.bw")


data_tracks <- list(Hap1_pADamID_LB1, Hap1_pADamID_LB2, Hap1_DamID, 
                    K562_pADamID_LB1, K562_pADamID_LB2, K562_DamID,
                    HCT116_pADamID_LB1, HCT116_pADamID_LB2, HCT116_DamID,
                    RPE_pADamID_LB1, RPE_pADamID_LB2, RPE_pADamID_LAC, 
                    RPE_DamID)
names(data_tracks) <- file_names

# Let's combine the various bigwig files into one
# First, create a GRanges with all the bins
bins <- read.table("results/counts/bin-20kb/pADamID-Hap1_r4_Dam_semibad-Dam-20kb.counts.txt.gz",
                   sep = "\t")[, 1:3]
names(bins) <- c("seqnames", "start", "end")
bins$start <- bins$start + 1
bins <- as(bins, "GRanges")

# Add the data
mcols(bins)[, file_names] <- NA 

for (i in file_names) {
  track <- data_tracks[[i]]
  ovl <- findOverlaps(track, bins)
  mcols(bins)[subjectHits(ovl), i] <- track$score[queryHits(ovl)]
}


```

```{r knits setup}
library(knitr)
opts_chunk$set(dev=c('png', 'pdf'), fig.path = file.path(output_dir, "figures/"))
pdf.options(useDingbats = FALSE)
```


### 1) Plot

Plot a particular example region.

```{r plot, fig.width = 6, fig.height = 10}

PlotDataTracks <- function(bins, chr = "chr1", start = 1, end = 1e6) {
  
  # Get the data
  data <- bins[seqnames(bins) == chr & 
                 start(bins) >= start & 
                 end(bins) <= end]
  
  data <- as(data, "data.frame")
  
  # Melt the data
  data.melt <- melt(data, id.vars = c("seqnames", "start", "end", "width", "strand"))
  data.melt <- data.melt[complete.cases(data.melt), ]
  
  # Tweaking: color by pA-DamID / DamID
  data.melt$class <- sub("[^_]*_", "", data.melt$variable)
  data.melt$class <- factor(data.melt$class, levels = c("pADamID_LB1", 
                                                        "pADamID_LB2", 
                                                        "pADamID_LAC", 
                                                        "DamID"))
  
  # Plot the data
  plt <- ggplot(data.melt, aes(xmin = start / 1e6, xmax = end / 1e6, ymin = 0, ymax = value,
                               fill = class)) +
    geom_rect() +
    geom_hline(yintercept = 0, size = 0.5) +
    facet_grid(variable ~ ., scales = "free_y") +
    xlab(paste0(chr, " (Mb)")) +
    ylab("Score") +
    scale_x_continuous(expand = c(0, 0)) + 
    scale_y_continuous(expand = c(0, 0)) +
    scale_fill_brewer(palette = "Set1", guide = FALSE) +
    theme_classic()
  
  plot(plt)
  
}

PlotDataTracks(bins, 
               chr = "chr7", start = 149e6, end = 157e6)

```


### Conclusion

I need to decide and change the colors. This might be easier in illustrator, so 
I won't bother with it now.


### SessionInfo

```{r sessionInfo}

sessionInfo()

```





















